In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
sheets = pd.read_excel('/content/Regional Sales Dataset.xlsx', sheet_name=None)

In [ ]:
# Assign dataframes to each sheet
df_sales = sheets['Sales Orders']
df_customers = sheets['Customers']
df_products = sheets['Products']
df_regions = sheets['Regions']
df_state_reg = sheets['State Regions']
df_budgets = sheets['2017 Budgets']

In [ ]:
df_sales.head(5)

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270

In [ ]:
print("df_sales shape:", (df_sales.shape))
print("df_customers shape:", (df_customers.shape))
print("df_products shape:", (df_products.shape))
print("df_regions shape:", (df_regions.shape))
print("df_state_reg:", (df_state_reg.shape))
print("df_budgets:", (df_budgets.shape))

df_sales shape: (64104, 12)
df_customers shape: (175, 2)
df_products shape: (30, 2)
df_regions shape: (994, 15)
df_state_reg: (49, 3)
df_budgets: (30, 2)

In [ ]:
df_customers.head(5)

   Customer Index Customer Names
0               1  Geiss Company
1               2  Jaxbean Group
2               3     Ascend Ltd
3               4      Eire Corp
4               5   Blogtags Ltd

In [ ]:
df_regions.head(5)

,id,name,county,state_code,state,type,latitude,longitude,area_code,population,households,median_income,land_area,water_area,time_zone
0,1,Auburn,Lee County,AL,Alabama,City,32.60986,-85.48078,334,62059,21767,38342,152375113,2646161,America/Chicago
1,2,Birmingham,Shelby County/Jefferson County,AL,Alabama,City,33.52744,-86.79905,205,212461,89972,31061,378353942,6591013,America/Chicago
2,3,Decatur,Limestone County/Morgan County,AL,Alabama,City,34.57332,-86.99214,256,55437,22294,41496,141006257,17594716,America/Chicago
3,4,Dothan,Dale County/Houston County/Henry County,AL,Alabama,City,31.23370,-85.40682,334,68567,25913,42426,232166237,835468,America/Chicago
4,5,Hoover,Shelby County/Jefferson County,AL,Alabama,City,33.37695,-86.80558,205,84848,32789,77146,122016784,2553332,America/Chicago

In [ ]:
df_state_reg.head(5)

      Column1     Column2 Column3
0  State Code       State  Region
1          AL     Alabama   South
2          AR    Arkansas   South
3          AZ     Arizona    West
4          CA  California    West

In [ ]:
df_state_reg.columns = ['State Code', 'State', 'Region']
df_state_reg = df_state_reg[1:].reset_index(drop=True)
df_state_reg.head(5)

  State Code       State Region
0         AL     Alabama  South
1         AR    Arkansas  South
2         AZ     Arizona   West
3         CA  California   West
4         CO    Colorado   West

In [ ]:
df_products.head(5)

   Index Product Name
0      1    Product 1
1      2    Product 2
2      3    Product 3
3      4    Product 4
4      5    Product 5

In [ ]:
df_budgets.head(5)

  Product Name  2017 Budgets
0    Product 1   3016489.209
1    Product 2   3050087.565
2    Product 3   2642352.432
3    Product 4   2885560.824
4    Product 5   3925424.542

In [ ]:
df_sales.isnull().sum()

OrderNumber                  0
OrderDate                    0
Customer Name Index          0
Channel                      0
Currency Code                0
Warehouse Code               0
Delivery Region Index        0
Product Description Index    0
Order Quantity               0
Unit Price                   0
Line Total                   0
Total Unit Cost              0
dtype: int64

In [ ]:
 df_products.isnull().sum()

Index           0
Product Name    0
dtype: int64

In [ ]:
 df_regions.isnull().sum()

id               0
name             0
county           0
state_code       0
state            0
type             0
latitude         0
longitude        0
area_code        0
population       0
households       0
median_income    0
land_area        0
water_area       0
time_zone        0
dtype: int64

In [ ]:
df_state_reg.isnull().sum()

State Code    0
State         0
Region        0
dtype: int64

In [ ]:
df_budgets.isnull().sum()

Product Name    0
2017 Budgets    0
dtype: int64

In [ ]:
df = df_sales.merge(
    df_customers,
    how='left',
    left_on='Customer Name Index',
    right_on='Customer Index'
)

In [ ]:
df.head(5)

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost,Customer Index,Customer Names
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343,126,Rhynoodle Ltd
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918,96,Thoughtmix Ltd
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740,8,Amerisourc Corp
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852,42,Colgate-Pa Group
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270,73,Deseret Group

In [ ]:
 #merge with products
 df = df.merge(
     df_products,
     how='left',
     left_on='Product Description Index',
     right_on='Index'
 )

In [ ]:
df.head(5)

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost,Customer Index,Customer Names,Index,Product Name
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343,126,Rhynoodle Ltd,27,Product 27
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918,96,Thoughtmix Ltd,20,Product 20
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740,8,Amerisourc Corp,26,Product 26
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852,42,Colgate-Pa Group,7,Product 7
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270,73,Deseret Group,8,Product 8

In [ ]:
  df = df.merge(
    df_regions,
    how='left',
    left_on='Delivery Region Index',
    right_on='id'
)

In [ ]:
df.head(5)

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,...,type,latitude,longitude,area_code,population,households,median_income,land_area,water_area,time_zone
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,...,City,32.08354,-81.09983,912,145674,52798,36466,268318796,13908113,America/New York
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,...,City,39.61366,-86.10665,317,55586,20975,54176,72276415,1883,America/Indiana/Indianapolis
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,...,City,37.66243,-121.87468,925,79510,26020,124759,62489257,386195,America/Los Angeles
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,...,City,39.16533,-86.52639,812,84067,30232,30019,60221613,475857,America/Indiana/Indianapolis
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,...,Town,41.77524,-72.52443,959,58007,24141,63158,70972793,720300,America/New York

In [ ]:
import re
df.columns = [re.sub(r'[^a-zA-Z0-9_]', '', col).lower() for col in df.columns]
# print(df.columns.tolist()) # Debugging line - removed after identifying the issue
df = df.merge(
        df_state_reg[['State Code', 'Region']],
        how='left',
        left_on='state_code',
        right_on='State Code'
    )

In [ ]:
df = df.merge(
    df_budgets,
    how='left',
    left_on='productname',
    right_on='Product Name'
)

In [ ]:
df.to_csv('file.csv')

In [ ]:
cols_to_drop=['Customer Index','Index','id','State Code']
df=df.drop(columns=cols_to_drop,errors='ignore')
df.head(5)

,ordernumber,orderdate,customernameindex,channel,currencycode,warehousecode,deliveryregionindex,productdescriptionindex,orderquantity,unitprice,...,area_code,population,households,median_income,land_area,water_area,time_zone,Region,Product Name,2017 Budgets
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,...,912,145674,52798,36466,268318796,13908113,America/New York,South,Product 27,964940.231
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,...,317,55586,20975,54176,72276415,1883,America/Indiana/Indianapolis,Midwest,Product 20,2067108.120
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,...,925,79510,26020,124759,62489257,386195,America/Los Angeles,West,Product 26,5685138.270
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,...,812,84067,30232,30019,60221613,475857,America/Indiana/Indianapolis,Midwest,Product 7,889737.555
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,...,959,58007,24141,63158,70972793,720300,America/New York,Northeast,Product 8,1085037.329

In [ ]:
#convert all columns to lower case
df.columns = df.columns.str.lower()
df.columns.values

array(['ordernumber', 'orderdate', 'customernameindex', 'channel',
       'currencycode', 'warehousecode', 'deliveryregionindex',
       'productdescriptionindex', 'orderquantity', 'unitprice',
       'linetotal', 'totalunitcost', 'customerindex', 'customernames',
       'index', 'productname', 'name', 'county', 'state_code', 'state',
       'type', 'latitude', 'longitude', 'area_code', 'population',
       'households', 'median_income', 'land_area', 'water_area',
       'time_zone', 'region', 'product name', '2017 budgets'],
      dtype=object)

In [ ]:
cols_to_keep = [
    'ordernumber',
    'orderdate',
    'customernames',
    'channel',
    'product name',
    'orderquantity',
    'unitprice',
    'linetotal',
    'totalunitcost',
    'state_code',
    'county',
    'state',
    'region',
    'latitude',
    'longitude',
    '2017 budgets' # Added to keep the merged budget column
]

In [ ]:
df = df[cols_to_keep]

In [ ]:
df.head(5)

,ordernumber,orderdate,customernames,channel,product name,orderquantity,unitprice,linetotal,totalunitcost,state_code,county,state,region,latitude,longitude,2017 budgets
0,SO - 000225,2014-01-01,Rhynoodle Ltd,Wholesale,Product 27,6,2499.1,14994.6,1824.343,GA,Chatham County,Georgia,South,32.08354,-81.09983,964940.231
1,SO - 0003378,2014-01-01,Thoughtmix Ltd,Distributor,Product 20,11,2351.7,25868.7,1269.918,IN,Johnson County,Indiana,Midwest,39.61366,-86.10665,2067108.120
2,SO - 0005126,2014-01-01,Amerisourc Corp,Wholesale,Product 26,6,978.2,5869.2,684.740,CA,Alameda County,California,West,37.66243,-121.87468,5685138.270
3,SO - 0005614,2014-01-01,Colgate-Pa Group,Export,Product 7,7,2338.3,16368.1,1028.852,IN,Monroe County,Indiana,Midwest,39.16533,-86.52639,889737.555
4,SO - 0005781,2014-01-01,Deseret Group,Wholesale,Product 8,8,2291.4,18331.2,1260.270,CT,Hartford County,Connecticut,Northeast,41.77524,-72.52443,1085037.329

In [ ]:
df = df.rename(columns={
   'ordernumber': 'order_number',
   'orderdate': 'order_date',
    'customernames': 'customer_name',
    'productname_x': 'product_name',
    'orderquantity': 'order_quantity',
    'unitprice': 'unit_price',
    'linetotal': 'revenue',
    'totalunitcost': 'cost',
    'state_code_y': 'state',
    'latitude_y': 'lat',
    'longitude_y': 'lon',
    '2017 budgets': 'budget' # Renamed after being correctly merged and lowercased
})
df.head(1)

,order_number,order_date,customer_name,channel,product name,order_quantity,unit_price,revenue,cost,state_code,county,state,region,latitude,longitude,budget
0,SO - 000225,2014-01-01,Rhynoodle Ltd,Wholesale,Product 27,6,2499.1,14994.6,1824.343,GA,Chatham County,Georgia,South,32.08354,-81.09983,964940.231

In [ ]:
#blank out budgets for non-2017 orders
print('Columns before operation:', df.columns.tolist())
print('DataFrame head before operation:')
print(df.head())
df.loc[df['order_date'].dt.year != 2017, 'budget'] = pd.NA
df[['order_date','product name','revenue','budget']].head(5)

Columns before operation: ['order_number', 'order_date', 'customer_name', 'channel', 'product name', 'order_quantity', 'unit_price', 'revenue', 'cost', 'state_code', 'county', 'state', 'region', 'latitude', 'longitude', 'budget']
DataFrame head before operation:
   order_number order_date     customer_name      channel product name  \
0   SO - 000225 2014-01-01     Rhynoodle Ltd    Wholesale   Product 27
1  SO - 0003378 2014-01-01    Thoughtmix Ltd  Distributor   Product 20
2  SO - 0005126 2014-01-01   Amerisourc Corp    Wholesale   Product 26
3  SO - 0005614 2014-01-01  Colgate-Pa Group       Export    Product 7
4  SO - 0005781 2014-01-01     Deseret Group    Wholesale    Product 8

   order_quantity  unit_price  revenue      cost state_code           county  \
0               6      2499.1  14994.6  1824.343         GA   Chatham County
1              11      2351.7  25868.7  1269.918         IN   Johnson County
2               6       978.2   5869.2   684.740         CA   Alameda County
3               7      2338.3  16368.1  1028.852         IN    Monroe County
4               8      2291.4  18331.2  1260.270         CT  Hartford County

         state     region  latitude  longitude  budget
0      Georgia      South  32.08354  -81.09983     NaN
1      Indiana    Midwest  39.61366  -86.10665     NaN
2   California       West  37.66243 -121.87468     NaN
3      Indiana    Midwest  39.16533  -86.52639     NaN
4  Connecticut  Northeast  41.77524  -72.52443     NaN

  order_date product name  revenue  budget
0 2014-01-01   Product 27  14994.6     NaN
1 2014-01-01   Product 20  25868.7     NaN
2 2014-01-01   Product 26   5869.2     NaN
3 2014-01-01    Product 7  16368.1     NaN
4 2014-01-01    Product 8  18331.2     NaN

In [ ]:
df[['order_date','product name','revenue','budget']].head(5)

  order_date product name  revenue  budget
0 2014-01-01   Product 27  14994.6     NaN
1 2014-01-01   Product 20  25868.7     NaN
2 2014-01-01   Product 26   5869.2     NaN
3 2014-01-01    Product 7  16368.1     NaN
4 2014-01-01    Product 8  18331.2     NaN

In [ ]:
df.to_csv('final.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_number    64104 non-null  object
 1   order_date      64104 non-null  datetime64[ns]
 2   customer_name   64104 non-null  object
 3   channel         64104 non-null  object
 4   product name    64104 non-null  object
 5   order_quantity  64104 non-null  int64
 6   unit_price      64104 non-null  float64
 7   revenue         64104 non-null  float64
 8   cost            64104 non-null  float64
 9   state_code      64104 non-null  object
 10  county          64104 non-null  object
 11  state           64104 non-null  object
 12  region          64104 non-null  object
 13  latitude        64104 non-null  float64
 14  longitude       64104 non-null  float64
 15  budget          15263 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(8)
memory usage: 7.8+ MB

In [ ]:
#filter the data set
df_2017=df[df['order_date'].dt.year == 2017]

In [ ]:
df.isnull().sum()

order_number          0
order_date            0
customer_name         0
channel               0
product name          0
order_quantity        0
unit_price            0
revenue               0
cost                  0
state_code            0
county                0
state                 0
region                0
latitude              0
longitude             0
budget            48841
dtype: int64

In [ ]:
df_2017.head(5)

,order_number,order_date,customer_name,channel,product name,order_quantity,unit_price,revenue,cost,state_code,county,state,region,latitude,longitude,budget
46363,SO - 0002544,2017-01-01,NCS Group,Wholesale,Product 30,6,1239.5,7437.0,1028.785,NJ,Hudson County,New Jersey,Northeast,40.77955,-74.02375,1011609.684
46364,SO - 0006431,2017-01-01,Epic Group,Wholesale,Product 13,5,1829.1,9145.5,1207.206,CO,Mesa County,Colorado,West,39.06387,-108.55065,3720639.645
46365,SO - 0007491,2017-01-01,State Ltd,Wholesale,Product 15,9,2412.0,21708.0,1664.280,CA,Los Angeles County,California,West,33.96168,-118.35313,3299478.315
46366,SO - 0008741,2017-01-01,Fivebridge Ltd,Wholesale,Product 8,8,904.5,7236.0,750.735,IA,Dubuque County,Iowa,Midwest,42.50056,-90.66457,1085037.329
46367,SO - 0009295,2017-01-01,Tagfeed Ltd,Wholesale,Product 2,12,1112.2,13346.4,811.906,FL,Hernando County,Florida,South,28.47689,-82.52546,3050087.565

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

df.to_csv('/content/drive/MyDrive/cleaned_sales_data.csv', index=False)

Mounted at /content/drive

NameError: name 'df' is not defined

In [ ]:
df.head(5)

,order_number,order_date,customer_name,channel,product name,order_quantity,unit_price,revenue,cost,state_code,county,state,region,latitude,longitude,budget
0,SO - 000225,2014-01-01,Rhynoodle Ltd,Wholesale,Product 27,6,2499.1,14994.6,1824.343,GA,Chatham County,Georgia,South,32.08354,-81.09983,NaN
1,SO - 0003378,2014-01-01,Thoughtmix Ltd,Distributor,Product 20,11,2351.7,25868.7,1269.918,IN,Johnson County,Indiana,Midwest,39.61366,-86.10665,NaN
2,SO - 0005126,2014-01-01,Amerisourc Corp,Wholesale,Product 26,6,978.2,5869.2,684.740,CA,Alameda County,California,West,37.66243,-121.87468,NaN
3,SO - 0005614,2014-01-01,Colgate-Pa Group,Export,Product 7,7,2338.3,16368.1,1028.852,IN,Monroe County,Indiana,Midwest,39.16533,-86.52639,NaN
4,SO - 0005781,2014-01-01,Deseret Group,Wholesale,Product 8,8,2291.4,18331.2,1260.270,CT,Hartford County,Connecticut,Northeast,41.77524,-72.52443,NaN

In [ ]:
df['total_cost'] = df['order_quantity'] * df['cost']

In [ ]:
df['profit'] = df['revenue'] - df['cost']
df['profit_margin_pct'] = df['profit'] / df['revenue']*100

In [ ]:
df.head(5)

,order_number,order_date,customer_name,channel,product name,order_quantity,unit_price,revenue,cost,state_code,county,state,region,latitude,longitude,budget,total_cost,profit,profit_margin_pct
0,SO - 000225,2014-01-01,Rhynoodle Ltd,Wholesale,Product 27,6,2499.1,14994.6,1824.343,GA,Chatham County,Georgia,South,32.08354,-81.09983,NaN,10946.058,13170.257,87.833333
1,SO - 0003378,2014-01-01,Thoughtmix Ltd,Distributor,Product 20,11,2351.7,25868.7,1269.918,IN,Johnson County,Indiana,Midwest,39.61366,-86.10665,NaN,13969.098,24598.782,95.090909
2,SO - 0005126,2014-01-01,Amerisourc Corp,Wholesale,Product 26,6,978.2,5869.2,684.740,CA,Alameda County,California,West,37.66243,-121.87468,NaN,4108.440,5184.460,88.333333
3,SO - 0005614,2014-01-01,Colgate-Pa Group,Export,Product 7,7,2338.3,16368.1,1028.852,IN,Monroe County,Indiana,Midwest,39.16533,-86.52639,NaN,7201.964,15339.248,93.714286
4,SO - 0005781,2014-01-01,Deseret Group,Wholesale,Product 8,8,2291.4,18331.2,1260.270,CT,Hartford County,Connecticut,Northeast,41.77524,-72.52443,NaN,10082.160,17070.930,93.125000

In [ ]:


# 4. Extract full month name from order_date for labeling (e.g., 'January', 'February')
df['order_month_name'] = df['order_date'].dt.month_name()

# 5. Extract month number from order_date for correct sorting (1–12)
df['order_month_num'] = df['order_date'].dt.month

# 6. (Optional) Display the updated DataFrame
df

,order_number,order_date,customer_name,channel,product name,order_quantity,unit_price,revenue,cost,state_code,...,state,region,latitude,longitude,budget,total_cost,profit,profit_margin_pct,order_month_name,order_month_num
0,SO - 000225,2014-01-01,Rhynoodle Ltd,Wholesale,Product 27,6,2499.1,14994.6,1824.343,GA,...,Georgia,South,32.08354,-81.09983,NaN,10946.058,13170.257,87.833333,January,1
1,SO - 0003378,2014-01-01,Thoughtmix Ltd,Distributor,Product 20,11,2351.7,25868.7,1269.918,IN,...,Indiana,Midwest,39.61366,-86.10665,NaN,13969.098,24598.782,95.090909,January,1
2,SO - 0005126,2014-01-01,Amerisourc Corp,Wholesale,Product 26,6,978.2,5869.2,684.740,CA,...,California,West,37.66243,-121.87468,NaN,4108.440,5184.460,88.333333,January,1
3,SO - 0005614,2014-01-01,Colgate-Pa Group,Export,Product 7,7,2338.3,16368.1,1028.852,IN,...,Indiana,Midwest,39.16533,-86.52639,NaN,7201.964,15339.248,93.714286,January,1
4,SO - 0005781,2014-01-01,Deseret Group,Wholesale,Product 8,8,2291.4,18331.2,1260.270,CT,...,Connecticut,Northeast,41.77524,-72.52443,NaN,10082.160,17070.930,93.125000,January,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64099,SO - 0007573,2018-02-28,Dazzlesphe Corp,Wholesale,Product 26,12,1815.7,21788.4,980.478,PA,...,Pennsylvania,Northeast,40.15511,-74.82877,NaN,11765.736,20807.922,95.500000,February,2
64100,SO - 0007706,2018-02-28,Yombu Corp,Export,Product 21,6,864.3,5185.8,579.081,IL,...,Illinois,Midwest,42.11030,-88.03424,NaN,3474.486,4606.719,88.833333,February,2
64101,SO - 0007718,2018-02-28,Bath Group,Distributor,Product 13,11,3953.0,43483.0,2648.510,FL,...,Florida,South,26.24453,-80.20644,NaN,29133.610,40834.490,93.909091,February,2
64102,SO - 0008084,2018-02-28,Linklinks Ltd,Distributor,Product 20,7,3959.7,27717.9,2930.178,NY,...,New York,Northeast,42.91002,-78.74182,NaN,20511.246,24787.722,89.428571,February,2
64103,SO - 0008654,2018-02-28,SAFEWAY Ltd,Distributor,Product 15,8,998.3,7986.4,848.555,OR,...,Oregon,West,45.48706,-122.80371,NaN,6788.440,7137.845,89.375000,February,2

In [ ]:
df.to_csv('1final.csv')